/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sunxuedian_Jni_Test */

#ifndef _Included_com_sunxuedian_Jni_Test
#define _Included_com_sunxuedian_Jni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sunxuedian_Jni_Test
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sunxuedian_Jni_1Test_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_sunxuedian_Jni_Test
 * Method:    setString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sunxuedian_Jni_1Test_setString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
